# 복습

In [4]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

data = {
    "study_hours" : [1, 2, 3, 3, 4, 4, 5, 6, 7, 8],
    "attendance" : [50, 55, 60, 80, 60, 75, 75, 80, 90, 95],
    "pass_fail" : [0, 0, 0, 1, 0, 1, 1, 1, 1, 1] 
}
df = pd.DataFrame(data)

# 입력값과 정답 분리
X = df[["study_hours", "attendance"]] # 입력값 (x = 입력값)
y = df["pass_fail"] # 정답

model = DecisionTreeClassifier(random_state=42)
model.fit(X, y)

print("데이터 준비 완료")
print(f"학생 수 :{len(df)}명") #학생 수 : %%명

데이터 준비 완료
학생 수 :10명

# 모델 정확도

- 학습에 사용한 데이터로 정확도 확인

In [5]:
accuracy = model.score(X,y)
print("모델 정확도:", accuracy)
print(f"모델 정확도: {accuracy * 100}%")

모델 정확도: 1.0
모델 정확도: 100.0%

In [6]:
# 모델이 어떤 예측을 했는지 확인
predictions = model.predict(X)

# Columns - 공부시간, 출석률, 실제, 예측, 결과
# 대부분의 결과값은 values로 부른다
# zip() => zip([1,2,3], [4,5,6]) => [(1,4), (2,5), (3,6)]
# 실제값과 예측값을 한쌍으로 묶어서
# for a, p in zip(y.values, predictions)
# if (a == p): 
#      print("o")
# else:
#      print("x")
result = pd.DataFrame({
    "공부시간": X["study_hours"].values,       # Study_hours의 데이터 값을 불러옴
    "출석률": X["attendance"].values,         # Attendance의 데이터 값을 불러옴
    "실제": y.values,                        # y의 데이터 값을 불러옴 
    "예측": predictions,                     # predictions는 모델이 예측한 값
    "결과": ["o" if a == p else "x" for a, p in zip(y.values, predictions)]     # zip() 함수는 실제값과 예측값을 압축해서 결과를 만듬  
})

result

   공부시간  출석률  실제  예측 결과
0     1   50   0   0  o
1     2   55   0   0  o
2     3   60   0   0  o
3     3   80   1   1  o
4     4   60   0   0  o
5     4   75   1   1  o
6     5   75   1   1  o
7     6   80   1   1  o
8     7   90   1   1  o
9     8   95   1   1  o

# 딕셔너리 Dictionary

다른 언어에선 json , Ai에선 Dictionary라고 불림 

key-value 한쌍으로 이루어진 집합(자료형)

List -> 번호표가 있는 사물함 (0번, 1번, 2번, ...)

Dictionary -> 이름표가 있는 사물함(학번, 이름, 학년, ...)

In [7]:
#리스트

student_list = ["kim", 20, 50]
print(f"리스트에서 이름 출력: {student_list[0]}") # 리스트에서 이름 출력: kim

# 딕셔너리
student_dict = {"name": "kim", "age": 20, "score": 50}  
print(f"딕셔너리에서 이름 출력: {student_dict['name']}") # 딕셔너리에서 이름 출력: kim

리스트에서 이름 출력: kim
딕셔너리에서 이름 출력: kim

In [8]:
person = {
    "name": "아무개",
    "age": 20,
    "major": "Ai 응용프래그래밍"
}

# 전체 출력
print(person)                 # person 자체를 출력
print(person["age"])          # person 딕셔너리에서 age 키에 해당하는 값을 출력
print(person["major"])        # person 딕셔너리에서 major 키에 해당하는 값을 출력

{'name': '아무개', 'age': 20, 'major': 'Ai 응용프래그래밍'}
20
Ai 응용프래그래밍

In [9]:
person["age"] = 21
print(person["age"], person)          

# 성별 추가
person["gender"] = "male"
print(person)

# 성별 삭제
del person["gender"]
print(person)

21 {'name': '아무개', 'age': 21, 'major': 'Ai 응용프래그래밍'}
{'name': '아무개', 'age': 21, 'major': 'Ai 응용프래그래밍', 'gender': 'male'}
{'name': '아무개', 'age': 21, 'major': 'Ai 응용프래그래밍'}

# 문제

사과, 바나나, 포도는 각 1000, 2000, 3000원 이다.
 - 딕셔너리 로그 출력

사과의 가격을 10% 할인하고 바나나는 13% 인상했을 때,
 - Python 코드로 작성

사과, 바나나, 포도의 가격표를 표시하세요. 
 - 로그 출력 (DataFrame 사용)

In [10]:
# Dictionary 로그 출력

fruits = {
    "사과": 1000,
    "바나나": 2000,
    "포도": 3000
}

print(fruits)   # 전체 딕셔너리 출력

{'사과': 1000, '바나나': 2000, '포도': 3000}

In [11]:
# 과일 변동 가격을 Python 코드로 작성

fruits = {
    "사과": 1000,
    "바나나": 2000,
    "포도": 3000
}

dis_apple = fruits["사과"] * (1 - 0.1)        # 사과 10% 할인
inc_banana = fruits["바나나"] * (1 + 0.13)    # 바나나 13% 인상

print(f"사과 할인 가격 : {dis_apple}원")
print(f"바나나 인상 가격 : {inc_banana}원")

사과 할인 가격 : 900.0원
바나나 인상 가격 : 2260.0원

In [12]:
# 사과, 바나나, 포도 가격을 DataFrame을 적용해서 작성

dic_fruits = {
    "과일": ["사과", "바나나", "포도"],
    "기존 가격": [fruits["사과"], fruits["바나나"], fruits["포도"]],
    "최종 가격": [int(dis_apple),int(inc_banana), fruits["포도"]]  # 사과는 10% 할인, 바나나는 13% 인상, 포도는 변동 없음
}
    
df_fruits = pd.DataFrame(dic_fruits)

df_fruits

    과일  기존 가격  최종 가격
0   사과   1000    900
1  바나나   2000   2260
2   포도   3000   3000

In [13]:


fruits = {
    "사과": 1000,
    "바나나": 2000,
    "포도": 3000
}

dis_apple = fruits["사과"] * (1 - 0.1)     
inc_banana = fruits["바나나"] * (1 + 0.13)


dic_fruits = {
    "과일": ["사과", "바나나", "포도"],
    "기존 가격": [fruits["사과"], fruits["바나나"], fruits["포도"]],
    "최종 가격": [int(dis_apple),int(inc_banana), fruits["포도"]]  
}
    
df_fruits = pd.DataFrame(dic_fruits)

df_fruits

    과일  기존 가격  최종 가격
0   사과   1000    900
1  바나나   2000   2260
2   포도   3000   3000

## 딕셔너리와 반복문을 함께 사용

In [14]:
scores = {
    "국어": 88, 
    "수학": 76,
    "영어": 92
}

# 로그 출력---
# 국어: 88점
# 수학: 76점
# 영어: 92점

for subject, score in scores.items(): # items()는 딕셔너리의 키와 값을 뜻하는 함수?
    print(f"{subject}: {score}점")

국어: 88점
수학: 76점
영어: 92점

In [15]:
# 80점 이상인 과목만 출력
for subject, score in scores.items():
    if score >= 80:
        print(f"80점 이상인 과목: {subject}")

80점 이상인 과목: 국어
80점 이상인 과목: 영어

# Pandas DataFrame 다루기

In [16]:
data = {
    "study_hours" : [1, 2, 3, 3, 4, 4, 5, 6, 7, 8],
    "attendance" : [50, 55, 60, 80, 60, 75, 75, 80, 90, 95],
    "pass_fail" : [0, 0, 0, 1, 0, 1, 1, 1, 1, 1] 
}

df = pd.DataFrame(data)     #  데이터프레임 생성    
df

   study_hours  attendance  pass_fail
0            1          50          0
1            2          55          0
2            3          60          0
3            3          80          1
4            4          60          0
5            4          75          1
6            5          75          1
7            6          80          1
8            7          90          1
9            8          95          1

In [17]:
# 상위 3줄만 보기

print(df.head(3))      
df.head(3)              # df는  표 형태로 생성

   study_hours  attendance  pass_fail
0            1          50          0
1            2          55          0
2            3          60          0

   study_hours  attendance  pass_fail
0            1          50          0
1            2          55          0
2            3          60          0

In [18]:
# 기본 통계 보기
# count - 데이터 개수
# mean - 평균 (전체 나누기 개수)
# std - 표준편차 (평균에서 얼마나 퍼져있는지, 클수록 편차가 큼)
# min - 최솟값
# 25% - 하위 25% 지점의 값 
# 50% - 중간값
# 75% - 상위 25% 지점의 값
# max - 최댓값
df.describe()

       study_hours  attendance  pass_fail
count    10.000000   10.000000  10.000000
mean      4.300000   72.000000   0.600000
std       2.213594   15.129074   0.516398
min       1.000000   50.000000   0.000000
25%       3.000000   60.000000   0.000000
50%       4.000000   75.000000   1.000000
75%       5.750000   80.000000   1.000000
max       8.000000   95.000000   1.000000

In [19]:
# 조건으로 데이터 골라내기

high_attendance = df[df["attendance"] >= 70]  # 출석률이 70 이상인 데이터만 출력
# high_attendance


pass_students = df[df["pass_fail"] == 1]      # 합격한 학생만 출력
pass_students

   study_hours  attendance  pass_fail
3            3          80          1
5            4          75          1
6            5          75          1
7            6          80          1
8            7          90          1
9            8          95          1

## 날씨 예측

In [20]:
# 데이터 준비

weather_data = {
    "clouds" : [10, 20, 30, 50, 60, 70, 80, 90, 95, 40],
    "humidity" : [30, 35, 40, 55, 65, 70, 80, 85, 90, 45],
    "umbrella" : [0, 0, 0, 0, 1, 1, 1, 1, 1, 0]
}

weather_df = pd.DataFrame(weather_data)
weather_df

   clouds  humidity  umbrella
0      10        30         0
1      20        35         0
2      30        40         0
3      50        55         0
4      60        65         1
5      70        70         1
6      80        80         1
7      90        85         1
8      95        90         1
9      40        45         0

In [21]:
# 입력값과 정답 분리

X_weather = weather_df[["clouds", "humidity"]]         # 입력값
y_weather = weather_df["umbrella"]                     # 정답

print("입력값과 정답 분리 완료!")

입력값과 정답 분리 완료!

In [22]:
# 모델 만들기 + 학습

weather_model = DecisionTreeClassifier(random_state=42) 
weather_model.fit(X_weather, y_weather)                  # fit() 함수는 모델을 학습시키는 함수
print("모델 학습 완료!")

모델 학습 완료!

In [23]:
# 예측하기
test_weather = pd.DataFrame([
    [20, 35], # 구름 적음, 습도 낮음
    [55, 60], # 구름 보통, 습도 보통
    [85, 88], # 구름 많음, 습도 높음
], columns=["clouds", "humidity"])

predictions = weather_model.predict(test_weather)

## 문제

아래 로그 개별 출력
- 구름?%,습도 ?% -> 우산 필요|불필요
예시) 구름 20%, 습도 35% -> 우산 불필요

In [24]:
for i in range(len(test_weather)) :
    if predictions[i] == 1 :
        print(f"구름 {test_weather.iloc[i, 0]}%, 습도{test_weather.iloc[i, 1]}% -> 우산 필요")
    else :
        print(f"구름 {test_weather.iloc[i, 0]}%, 습도{test_weather.iloc[i, 1]}% -> 우산 불필요")

구름 20%, 습도35% -> 우산 불필요
구름 55%, 습도60% -> 우산 불필요
구름 85%, 습도88% -> 우산 필요

In [25]:
# 모델 정확도 구하기

acc = weather_model.score(X_weather, y_weather)        # acc = accuracy
print(f"모델 정확도: {acc * 100}%")

모델 정확도: 100.0%

In [26]:
# 모델 정확도 낮추기
# 애매한 데이터를 포함한 날씨 데이터

messy_data = {
    "clouds": [10, 20, 55, 55, 60, 70, 80, 90],
    "humidity": [30, 35, 60, 60, 65, 70, 80, 85],
    "umbrella": [0, 0, 0, 1, 1, 1, 1, 1],
}

messy_df = pd.DataFrame(messy_data)

X_messy = messy_df[["clouds", "humidity"]]
y_messy = messy_df["umbrella"]

messy_model = DecisionTreeClassifier(random_state=42)
messy_model.fit(X_messy, y_messy)

messy_acc = messy_model.score(X_messy, y_messy)
print(f"애매한 데이터 모델 정확도: {messy_acc * 100}%")

print()

messy_pred = messy_model.predict(X_messy)
result = pd.DataFrame({
    "구름": X_messy["clouds"].values,
    "습도": X_messy["humidity"].values,
    "실제": y_messy.values,
    "예측": messy_model.predict(X_messy),
    "결과": ["o" if a == p else "x" for a, p in zip(y_messy, messy_pred)]})

result

애매한 데이터 모델 정확도: 87.5%

   구름  습도  실제  예측 결과
0  10  30   0   0  o
1  20  35   0   0  o
2  55  60   0   0  o
3  55  60   1   0  x
4  60  65   1   1  o
5  70  70   1   1  o
6  80  80   1   1  o
7  90  85   1   1  o